# main text of home
title: 'Polak is writing | Blog'
author: Marcin Polak

email:
url: https://haker.dev/
description:
favicon: "assets/favicon/apple-touch-icon.png" # set the favicon of the site 

# Moving date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
moving:
  avatar_url: "https://github.com/polok/polok.github.com/blob/master/assets/avatar.png?raw=true" # avatar in about page
  about_you:
  date_format: "%b %d" # date format of posts in home page
  back_to: "Home" # In the post page, you have a back button above the title, you can custom the text by yourself.

# To enable google analytics, supply your token below
analytics-google: 'G-PY54NJGLEL'

# To enable piwik tracking, supply your url & site ID below
# analytics-piwik-url: 'piwik.my-host.com'
# analytics-piwik-id: 1

# if you don't want comments in your posts, leave categories empty
#disqus:
#  shortname: mydisqus # enter this from your disqus account
#  categories: [blog, project] # only show disqus for posts that have these categories

# if you don't have any of social below, comment the line
#facebook: myfacebook
#twitter: mytwitter
# google: mygoogle
# instagram: myinstagram
# pinterest: mypinterest
# linkedin: mylinkedin
# youtube: myyoutube
# spotify: myspotify
github: polok
# stackoverflow: 7044681/mystackoverflow
# quora: userquora
# reddit: username
#medium: medium
# vimeo: myvimeo
email: mpolak87@gmail.com

# Build settings
remote_theme: huangyz0918/moving

gems:
  - jemoji
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-paginate

jekyll-mentions:
    base_url: https://github.com
